version: '3.8'

services:
  mongo:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: 4
    env_file: .env
    environment:
      MONGO_REPLICA_HOST: ${DATABASE_HOST}
      MONGO_REPLICA_PORT: ${DATABASE_PORT}
      MONGO_COMMAND: 'mongo'
    ports:
      - '27018:27017'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'mongo',
          'admin',
          '--port',
          '27017',
          '--eval',
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
  nodejs:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL:
      AUTH_TOKEN_SECRET:
      AUTH_TOKEN_EXPIRATION:
    volumes:
      - .:/usr/src/myapp
      - /usr/src/myapp/node_modules
    ports:
      - '3000:3000'
